#\u7AEF\u53E3
server:
  port: 8779

#\u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    username: root
    password: onepiece1996
    url: jdbc:mysql://localhost:3306/mybatispuls?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikaric
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 12000
      max-lifetime: 30000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      connection-init-sql: set names utf8mb4
      read-only: false

mybatis-plus:
  type-enums-package: com.streamslience.simples.enums.mpslenum.enums.*
  global-config: # \u5168\u5C40\u8BBE\u7F6E
    db-config: # \u6570\u636E\u5E93\u76F8\u5173\u8BBE\u7F6E
      id-type: uuid #\u4E3B\u952E\u7C7B\u578B  AUTO:"\u6570\u636E\u5E93ID\u81EA\u589E", INPUT:"\u7528\u6237\u8F93\u5165ID",ID_WORKER:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", UUID:"\u5168\u5C40\u552F\u4E00ID UUID";
      column-underline: true # \u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
      #capital-mode: true #\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
      logic-delete-value: D
      logic-not-delete-value: A
      table-prefix: xx_ # \u8868\u540D\u524D\u7F00
      table-underline: true # \u8868\u540D\u3001\u662F\u5426\u4F7F\u7528\u4E0B\u5212\u7EBF\u547D\u540D\uFF08\u9ED8\u8BA4 true:\u9ED8\u8BA4\u6570\u636E\u5E93\u8868\u4E0B\u5212\u7EBF\u547D\u540D\uFF09

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.streamslience.simples.enums.mpslenum: trace

