server:
  port: 8779

spring:
  datasource:
    username: root
    password: ???
    url: jdbc:p6spy:mysql://localhost:3306/mybatispuls?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # url: jdbc:mysql://localhost:3306/mybatispuls?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    # driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource # com.p6spy.engine.spy.P6DataSource
    hikari:
      pool-name: Hikaric
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 12000
      max-lifetime: 30000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      connection-init-sql: set names utf8mb4
      read-only: false

mybatis-plus:
  global-config:
    db-config:
      id-type:
      column-underline: true
      #capital-mode: true
      logic-delete-value: D
      logic-not-delete-value: A
      table-prefix: xx_
      table-underline: true

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.streamslience.simples.enums.mpslenum: trace

