#端口
server:
  port: 8786

#数据库配置
spring:
  datasource:
    username: root
    password: onepiece1996
    url: jdbc:mysql://localhost:3306/mybatispuls?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikaric
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 12000
      max-lifetime: 30000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      connection-init-sql: set names utf8mb4
      read-only: false

mybatis-plus:
  type-enums-package: com.streamslience.simples.enums.mpslenum.enums.*
  global-config: # 全局设置
    db-config: # 数据库相关设置
      id-type: uuid #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      column-underline: true # 驼峰下划线转换
      #capital-mode: true #数据库大写下划线转换
      logic-delete-value: D
      logic-not-delete-value: A
      table-prefix: xx_ # 表名前缀
      table-underline: true # 表名、是否使用下划线命名（默认 true:默认数据库表下划线命名）

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.streamslience.simples.enums.mpslenum: trace
