#端口
server:
  port: 8782

#数据库配置
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mybatispuls?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: ???
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 12000
      max-lifetime: 30000
      connection-timeout: 10000
      connection-init-sql:  set names utf8mb4
      connection-test-query: select 1
      read-only: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: D
      logic-not-delete-value: A
      column-format: true
      table-prefix: xx_



logging:
  level:
    com.streamslience.simples.typehandler.mpsltypehandler: trace
