server:
  port: 8780

spring:
  datasource:
    username: root
    password: ???
    url: jdbc:mysql://localhost:3306/mybatispuls?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 12000
      max-lifetime: 30000
      connection-timeout: 20000
      connection-test-query: select 1
      connection-init-sql: set names utf8mb4
      # read-only: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: xx_
      # column-format: f_%s_g # 格式化字段,对主键无效,不可以单独配置为 %s
      # capital-mode: true
      # column_underline: true
      #table-underline: true
      logic-delete-value: D
      logic-not-delete-value: A

logging:
  level:
    com.streamslience.simples.sqlparser.mpslsqlparser: debug